apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:EDfPqfURyqA+Z0kcQMJC,iv:Jc6Hri8c2Amd6qKwi7BMX+giPHhKEYV4wcJfiU7z10E=,tag:etpPMb/YHIERhgAkKVL9/g==,type:str]
sops:
  age:
    - recipient: age1rcpk958jus0pazdt4d0gc0mhqhqn55ajtq7s04e5fx24lhygv5uq5x0z5q
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDR3FNaHBTenpZSURFS0Fv
        OUhaWXRBMmR6bEpMNDU5TzlrUzlnNld5c0VjCnd0K0gyZmRtcXZoMEFtb0lXQm1L
        VnFjVHo2ZGFlR3loUzQyNjQ3NndOb2MKLS0tIDA4VWdveWRVclJ3NDdpQ0YyR0E2
        dnUrZVlsUm84bUhRYms4WVNjMnlLWTgKcSULnASmStg89el9663LVvX7bIZCFg3q
        FwF74IIwqQ2Ps8UopfRATt3DBj/srPgJ0xRdV/b7q4zY2r/Qr2r41A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-13T16:28:00Z"
  mac: ENC[AES256_GCM,data:H3uLEu0zVgCKjAM9uP9p0u/+HNxjJ2cFkbSJlBZJmxJ/0JI4f2J5gSkjVus4cHU55N6N6skYVifwage7x4220PQVrBaGY/HVlWsjurAZBchsBWAhJEP8x8SEr9yqY0DKdwDGtRLZC9ATd8UCK6cYZiKn9OxwAuj/vv0tm+HUAxc=,iv:XYOQxRQZx3q6vIJWayVf6h7JMMkNLhxO/gOAtO7qWV8=,tag:70qpdCBhMbHJoSOw6g4Lgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
